name: Build and Release

on:
  push:
    tags:
      - 'v*' # Запускается, когда ты создаешь тег версии (например v1.9.8)

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            artifact_name: vfetch.exe
            rid: win-x64
          - os: ubuntu-latest
            artifact_name: vfetch
            rid: linux-x64

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish
      run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=false -o ./publish

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.rid }}-bin
        path: ./publish/${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Windows Binary
      uses: actions/download-artifact@v3
      with:
        name: win-x64-bin
        path: ./release-files

    - name: Download Linux Binary
      uses: actions/download-artifact@v3
      with:
        name: linux-x64-bin
        path: ./release-files

    - name: Copy Installer
      run: cp install.py ./release-files/install.py

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./release-files/vfetch.exe
          ./release-files/vfetch
          ./release-files/install.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
