name: Build and Release

on:
  push:
    branches: [ main ] # Сделаем запуск при каждом пуше в main, чтобы проверить работу
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      # Автоматически находит любой файл .csproj в корне
      run: dotnet publish *.csproj -c Release -r ${{ matrix.os == 'windows-latest' && 'win-x64' || 'linux-x64' }} --self-contained true /p:PublishSingleFile=true -o ./publish

    - name: Rename Binaries
      shell: bash
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          mv ./publish/*.exe ./publish/vfetch.exe
        else
          # Находим бинарник (он будет называться как проект) и переименовываем в vfetch
          mv $(find ./publish -type f ! -name "*.*") ./publish/vfetch
        fi

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vfetch-${{ matrix.os }}
        path: ./publish/vfetch*

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download Artifacts
      uses: actions/download-artifact@v4
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./vfetch-windows-latest/vfetch.exe
          ./vfetch-ubuntu-latest/vfetch
          install.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
